### ISSUE TITLE
Axis values do not update correctly

### ISSUE THREAD

**Issue by kylerbrown** [margoliashlab/arfview#14]

**Comment by tbrawn** [comment]
Error1: When opening an eeg file and a label file together, the label file loads incorrectly (at least visually). This correct itself after using arrow key to move to next segment. (see error1 image in email)

Error2: y-axis: When changing the y-axis values, entering the first new value for negative or positive y-value correctly changes the view.  Changing the second value doesn't cause a correct change until moving to next segment.  While the data are correctly in the new y-value range, the y-axis doesn't update (see error2 image in email: y-axis should range from -100 to +100, but shows -100 to 6000. This can be corrected by using the mouse to manually adjust the y axis

Error 3: x-axis: When setting the x-axis, what is shown is slight off from what is entered. In error3 image in your email, the x-axis should be from 210.00 to 210.03.  It is slightly off.  This produces serious problems for viewing the epoch score and especially for editing epoch scores.  It is also sometimes slightly changes the x-range when moving through segments.

In general, it feels sluggish and can't keep up with how quickly I need to move through segments

**Comment by kylerbrown** [comment]
fixed by #15
