### ISSUE TITLE
keyboard shortcut for moving between entries

### ISSUE THREAD

**Issue by kylerbrown** [margoliashlab/arfview#2]
The down arrow used to work to view the next entry in an arf file. Now only selection by clicking seems to work. I'd like some kind of keyboard shortcut, down arrow or otherwise, to quickly move through an arf file.

Thanks!

**Comment by pmalonis** [comment]
I will add this, but in the meantime you can select all of the groups in the file using the Shift key and scroll through the plots to find a song.
