### ISSUE TITLE
Please change Ctrl+Shift+F selects the next dataset

### ISSUE THREAD

**Issue by dbals** [margoliashlab/arfview#6]
to something easier e.g. the space bar

**Comment by kylerbrown** [comment]
Hey all, I've made a pull request for changing the shortcut to the return key, I also added "Peter mode" which is "Ctrl+alt+shift+F". The docs should be updated with a clear list of all the shortcuts. @gfetterman are you up for that? Also the install.py might need some work.

@gfetterman  could you review this pull request? -> #7

**Comment by kylerbrown** [comment]
#7
